version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ums
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 30s
      retries: 10
      start_period: 40s

  app:
    build: .
    container_name: node-app
    restart: on-failure
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=staging
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=ums
      - PORT=5000
      - RUN_MIGRATIONS=true
      - RUN_SEEDS=true
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        until nc -z mysql 3306; do sleep 2; done &&
        echo 'Database is ready!' &&
        npx sequelize-cli db:migrate &&
        npx sequelize-cli db:seed:all &&
        npm start
      "

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge